{% set name = "conda-pack" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/{{ version }}.tar.gz
  sha256: df820a9d358e9ef04dffb261af7e4c4256f9c6a034af65350a9fe1e1fb2e2c36
  patches:
    - 0001_add_ash_support.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - conda-pack = conda_pack.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - setuptools
    - python >=3.7

test:
  commands:
    - conda-pack --help
    - pip check
  requires:
    - pip
  imports:
    - conda_pack

about:
  home: https://conda.github.io/conda-pack/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Package conda environments for redistribution
  description: |
    ``conda-pack`` is a command line tool for creating relocatable conda
    environments. This is useful for deploying code in a consistent environment,
    potentially in a location where python/conda isn't already installed.
  doc_url: https://conda.github.io/conda-pack/
  dev_url: https://github.com/conda/conda-pack

extra:
  recipe-maintainers:
    - jcrist
    - mcg1969
    - dbast
    - xhochy
